### PR TITLE
Add show staged diff command

### PR DESCRIPTION
**Pull request by syohex**
This is related to #129.
@AlexDaniel @arrdem  How about this ?

### CODE REVIEW

**Comment by AlexDaniel** [comment]
I am not sure. Ideally I would like to see both staged and unstaged changes at the same time, and being able to set ``git-gutter:staged-sign``. I am not sure how realistic this wish is, but that would be the best.

**Comment by AlexDaniel** [comment]
Hm. What's the idea behind closing this?

**Comment by syohex** [comment]
This is not #129 implementation.

**Comment by arrdem** [comment]
👍 cool! Thanks!

**Pull request closed without merging**
